apiVersion: v1
kind: ConfigMap
metadata:
  name: cropleaf-config
  namespace: cropleaf
data:
  POSTGRES_DB: cropleaf
  POSTGRES_USER: cropleaf
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_SSL: "false"
  DEBUG: "false"
  ALLOWED_HOSTS: "cropleaf.local,localhost,127.0.0.1"
  CSRF_TRUSTED_ORIGINS: "http://cropleaf.local,http://localhost"
